DELIMITER //
CREATE PROCEDURE RETURN_ALL_BILLS()
BEGIN
	SELECT BILL_ID, SUPPLIER_NAME, HOST_NAME, EVENT_NAME, AMOUNT, PAYMENT_STATUS
	FROM TABLE1 NATURAL JOIN TABLE2 NATURAL JOIN TABLE3;
END //
DELIMITER ;
