DELIMITER //
CREATE PROCEDURE RETURN_ALL_BILLS()
BEGIN
	SELECT BILL_ID, SUPPLIER_NAME, HOST_NAME, EVENT_NAME, AMOUNT, PAYMENT_STATUS
	FROM TABLE1 NATURAL JOIN TABLE2 NATURAL JOIN TABLE3;
END //
DELIMITER ;


-- Cursor Procedure

DELIMITER $$
CREATE PROCEDURE backup()
BEGIN
DECLARE done INT DEFAULT 0;
DECLARE HOST_ID INT(11);
DECLARE HOST_NAME VARCHAR(255);
DECLARE MOBILE_NUMBER VARCHAR(10);
DECLARE MAIL_ID VARCHAR(25);
DECLARE host_cursor CURSOR FOR SELECT * FROM hosts;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
OPEN host_cursor;
label: LOOP
FETCH host_cursor INTO HOST_ID, HOST_NAME, MOBILE_NUMBER, MAIL_ID;
INSERT INTO backup_table VALUES(HOST_ID, HOST_NAME, MOBILE_NUMBER, MAIL_ID);
IF done = 1 THEN LEAVE label;
END IF;
END LOOP;
CLOSE host_cursor;
END