CREATE TABLE IF NOT EXISTS HOSTS(
    HOST_ID INT AUTO_INCREMENT NOT NULL,
    HOST_NAME VARCHAR(255),
    MOBILE_NUMBER VARCHAR(10),
    MAIL_ID VARCHAR(25),
	PRIMARY KEY (HOST_ID));

CREATE TABLE IF NOT EXISTS EVENTS(
	EVENT_ID INT AUTO_INCREMENT NOT NULL,
    EVENT_NAME VARCHAR(255),
    EVENT_TYPE VARCHAR(255),
    EVENT_DATE_START DATE,
    EVENT_DATE_END DATE,
    EVENT_TIME_START TIME,
    EVENT_TIME_END TIME,
    VENUE VARCHAR(255),
    HOST_ID INT,
    PRIMARY KEY (EVENT_ID),
    FOREIGN KEY (HOST_ID) REFERENCES HOSTS(HOST_ID));

CREATE TABLE IF NOT EXISTS SUPPLIER(
    SUPPLIER_ID INT AUTO_INCREMENT NOT NULL,
    SUPPLIER_NAME VARCHAR(255), 
    DEPARTMENT VARCHAR(255),
    MAIL_ID VARCHAR(255),
    POINT_OF_CONTACT VARCHAR(255),
    MOBILE_NO VARCHAR(25),
    ADDRESS VARCHAR(255),
    PRIMARY KEY (SUPPLIER_ID));

CREATE TABLE IF NOT EXISTS BILLS(
    BILL_ID INT NOT NULL,
    DEALER VARCHAR(255),
    AMOUNT INT, 
    PAYMENT_STATUS VARCHAR(25),
    EVENT_ID INT, 
    HOST_ID INT, 
    SUPPLIER_ID INT,
    PRIMARY KEY (BILL_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),
    FOREIGN KEY (HOST_ID) REFERENCES HOSTS(HOST_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID));

CREATE TABLE IF NOT EXISTS SUPPLIED_FOR(
    EVENT_ID INT,
    SUPPLIER_ID INT, 
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID));

CREATE TABLE IF NOT EXISTS ATTENDEES(
    USER_ID INT NOT NULL AUTO_INCREMENT, 
    F_NAME VARCHAR(255),
    L_NAME VARCHAR(255),
    MOBILE_NUMBER INT, 
    MAIL_ID VARCHAR(255),
    DOB DATE, 
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    ADDRESS VARCHAR(255), 
    PRIMARY KEY (USER_ID));

CREATE TABLE IF NOT EXISTS ATTENDED_BY(
    USER_ID INT, 
    EVENT_ID INT, 
    FOREIGN KEY (USER_ID) REFERENCES ATTENDEES(USER_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID));

SELECT EVENT_ID, EVENT_NAME, USER_ID, F_NAME, L_NAME FROM (ATTENDED_BY NATURAL JOIN ATTENDEES NATURAL JOIN EVENTS)