DELIMITER //
CREATE TRIGGER MOBILE_NUMBER BEFORE INSERT ON ATTENDEES 
FOR EACH ROW 
BEGIN
	DECLARE LENGTH_NO INT;
    DECLARE MSG VARCHAR(255);
    SET MSG = ('Invalid Phone Number');
    SET LENGTH_NO = (SELECT LENGTH(NEW.MOBILE_NUMBER));
    IF (LENGTH_NO > 10 OR LENGTH_NO < 10) THEN
    	SIGNAL SQLSTATE '45000'
    	SET MESSAGE_TEXT = MSG;
    END IF;
END