CREATE VIEW TABLE1 AS
SELECT BILLS.BILL_ID, supplier.SUPPLIER_ID, supplier.SUPPLIER_NAME, BILLS.AMOUNT, BILLS.PAYMENT_STATUS
FROM BILLS 
LEFT JOIN supplier
ON BILLS.SUPPLIER_ID = supplier.SUPPLIER_ID;

CREATE VIEW TABLE2 AS
SELECT BILLS.BILL_ID, hosts.HOST_ID, hosts.HOST_NAME, BILLS.AMOUNT, BILLS.PAYMENT_STATUS
FROM BILLS 
LEFT JOIN HOSTS
ON BILLS.HOST_ID = hosts.HOST_ID;

CREATE VIEW TABLE3 AS 
SELECT BILLS.BILL_ID, events.EVENT_ID, events.EVENT_NAME, BILLS.AMOUNT, BILLS.PAYMENT_STATUS 
FROM BILLS LEFT JOIN events
ON BILLS.HOST_ID = events.EVENT_ID;